name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t zx252/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true zx252/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react_pages_test
          environment_name: Reactpagestest-env
          existing_bucket_name: elasticbeanstalk-us-east-1-930984322974
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
